### ISSUE TITLE
Altitude Restrictions Within Waypoints

### ISSUE THREAD

**Issue by ERAUAir1533** [gefs-plugins/fmc-requirejs#5]
I don't know if this is just me or not, but whenever I use altitude restrictions (the altitude set at waypoint) with VNAV, and it comes time to descend, the FMC (only ver. 52) forces a nosedive on my aircraft (more than -6000 feet per minute) and even when I try to regain control by turning Autopilot++ off, I can't regain control until I switch my controls over from keyboard to mouse. If you need anymore details on this, please feel free to contact me on FB.

**Comment by harryxue1999** [comment]
Yes, we are aware of this bug as other people have reported too. In the mean time I recommend reverting back to 0.5.1-beta until the issue is solved.

**Comment by ERAUAir1533** [comment]
Roger that. We will revert back to version 51. thanks!

On Aug 13, 2017 9:04 PM, Harry Xue <notifications@github.com> wrote:

Yes, we are aware of this bug as other people have reported too. In the mean time I recommend reverting back to 0.5.1-beta until the issue is solved.

**Comment by harryxue1999** [comment]
@Qantas94Heavy Maybe it is time to fix Autopilot's V/S mode input problem.

**Comment by harryxue1999** [comment]
OK, @ERAUAir1533 it would be great if you can recreate the problem with console logs.

**Comment by ERAUAir1533** [comment]
I apologize for the delayed response. Here are the logs! From what I can tell, it seems like the values for the descent are incorrect, but I don't know. I'll leave it to you to find out. 😄 
![fmc error 2](https://user-images.githubusercontent.com/30981949/29729535-8489ad04-89aa-11e7-91aa-2d20d688044f.PNG)
![fmc error](https://user-images.githubusercontent.com/30981949/29729534-8483fc06-89aa-11e7-8b31-6364c65bd925.PNG)

**Comment by harryxue1999** [comment]
Ok, these seem to be the debug log of autopilot (not your fault: production version of FMC does not have debug). Please recreate the bug after you paste the following line to the console: `fmc.require('debug').log=a=>console.log(a);`

**Comment by harryxue1999** [comment]
Better if the debug log is in text format. You can create a [gist](https://gist.github.com/)

**Comment by harryxue1999** [comment]
Hi, I have found the problem with this bug. 

If you are interested, basically V/S is set to a `-Infinity` value when the activated waypoint and the waypoint with the next altitude restriction is the same. This is because a certain statement in the VNAV logic did not reflect on the change in the route distance algorithm, a problem which makes the distance 0. Then a function to calculate climbrate returns the `-Infinity` value because any negative none zero number divided by 0 is `-Infinity`. 

With this bug fixed I have also fixed existing bugs with speed control and KIAS/Mach switching bug.

Thanks for submitting this bug report!
